# ============================================================================================
# FICHEIRO: application.properties (Configurações Globais do Spring Boot)
# ============================================================================================

# Define o nome oficial da tua aplicação dentro do ecossistema do Spring.
# Embora pareça um detalhe simples, isto é crucial se no futuro transformares este projeto
# numa arquitetura de microserviços. Ferramentas como o Spring Cloud (Eureka) ou
# sistemas de monitorização vão usar este nome exato para identificar quem está a fazer o quê.
spring.application.name=cinema-service

# Define a URL de conexão (Connection String) com a base de dados.
# - 'jdbc': Significa Java Database Connectivity (a ponte padrão do Java para bases de dados).
# - 'h2': É o tipo de base de dados que estamos a usar.
# - 'mem': Indica que a base de dados vai correr inteiramente na Memória RAM.
#          É super rápido para desenvolvimento, mas significa que sempre que reiniciares
#          a aplicação, os dados (como os teus utilizadores) vão desaparecer.
# - 'testdb': É o nome da base de dados que será criada na memória.
spring.datasource.url=jdbc:h2:mem:testdb

# Habilita a interface gráfica web da base de dados H2.
# Ao colocares como 'true', o Spring Boot cria uma rota automática (geralmente em http://localhost:8080/h2-console).
# Isto permite-te abrir o navegador, aceder à base de dados e rodar comandos SQL
# manualmente (SELECT, INSERT, etc.) para veres como os teus dados estão a ser guardados
# pela tua entidade User.
spring.h2.console.enabled=true

# Altera a ordem de inicialização da base de dados (Crucial para usar o ficheiro data.sql).
# Por padrão, o Spring Boot tenta correr o teu ficheiro 'data.sql' (para inserir dados)
# ANTES do Hibernate (JPA) ler as tuas anotações @Entity e criar as tabelas.
# Se isso acontecer, dá erro, porque ele tenta inserir dados numa tabela que ainda não existe.
# Ao definires isto como 'true', dizes ao Spring:
# "Espera! Deixa o Hibernate criar a tabela 'users' primeiro e só depois corre o meu script de inserção."
spring.jpa.defer-datasource-initialization=true